/**
 * Adapter for Hermes Tool: 'browser_get_images'
 * Execution Tier: 3 (Tier 3: Delegated to Host Daemon (Port 8001 / WebSocket / REST))
 * Auto-generated by sync_upstream_hermes.py
 */

export async function execute_browser_get_images(args = {}, context = {}) {
    // Tier 3 execution: forward to Webcom Host Daemon (Port 8001)
    console.log(`[Adapter] Delegating browser_get_images to Host Daemon...`, args);
    const resp = await context.callDaemon("/api/hermes/execute_tool", {
        name: "browser_get_images",
        arguments: args
    });
    return resp;
}
