/**
 * Adapter for Hermes Tool: 'comfyui_nodes'
 * Execution Tier: 3 (Tier 3: Delegated to Host Daemon (Port 8001 / WebSocket / REST))
 * Auto-generated by sync_upstream_hermes.py
 */

export async function execute_comfyui_nodes(args = {}, context = {}) {
    // Tier 3 execution: forward to Webcom Host Daemon (Port 8001)
    console.log(`[Adapter] Delegating comfyui_nodes to Host Daemon...`, args);
    const resp = await context.callDaemon("/api/hermes/execute_tool", {
        name: "comfyui_nodes",
        arguments: args
    });
    return resp;
}
