/**
 * Adapter for Hermes Tool: 'computer_use'
 * Execution Tier: 3 (Tier 3: Delegated to Host Daemon (Port 8001 / WebSocket / REST))
 * Auto-generated by sync_upstream_hermes.py
 */

export async function execute_computer_use(args = {}, context = {}) {
    // Tier 3 execution: forward to Webcom Host Daemon (Port 8001)
    console.log(`[Adapter] Delegating computer_use to Host Daemon...`, args);
    const resp = await context.callDaemon("/api/hermes/execute_tool", {
        name: "computer_use",
        arguments: args
    });
    return resp;
}
