/**
 * Adapter for Hermes Tool: 'gpu_info'
 * Execution Tier: 3 (Tier 3: Delegated to Host Daemon (Port 8001 / WebSocket / REST))
 * Auto-generated by sync_upstream_hermes.py
 */

export async function execute_gpu_info(args = {}, context = {}) {
    // Tier 3 execution: forward to Webcom Host Daemon (Port 8001)
    console.log(`[Adapter] Delegating gpu_info to Host Daemon...`, args);
    const resp = await context.callDaemon("/api/hermes/execute_tool", {
        name: "gpu_info",
        arguments: args
    });
    return resp;
}
