/**
 * Adapter for Hermes Tool: 'ha_list_entities'
 * Execution Tier: 3 (Tier 3: Delegated to Host Daemon (Port 8001 / WebSocket / REST))
 * Auto-generated by sync_upstream_hermes.py
 */

export async function execute_ha_list_entities(args = {}, context = {}) {
    // Tier 3 execution: forward to Webcom Host Daemon (Port 8001)
    console.log(`[Adapter] Delegating ha_list_entities to Host Daemon...`, args);
    const resp = await context.callDaemon("/api/hermes/execute_tool", {
        name: "ha_list_entities",
        arguments: args
    });
    return resp;
}
